### ISSUE TITLE
About the main difference between SimGRACE and GraphCL？

### ISSUE THREAD

**Issue by xdjwolf** [junxia97/SimGRACE#1]
Dear，Jun Xia

        Have you finished your code about SimGRACE， I found there‘s little difference with GraphCL such as the _unsupervised_TU_ folder.

**Comment by junxia97** [comment]
Hi,
Thanks for your interest! You can check the file named as 'simgrace.py' carefully. We substitue the data augmentations in GraphCL with encoder perturbations in line 240.
