### ISSUE TITLE
unsupervised learning 训练过程中损失函数为负

### ISSUE THREAD

**Issue by ghj9922** [junxia97/SimGRACE#5]
作者您好！我在unsupervised learning训练过程中loss变成了负数，请问有出现过这种问题吗？

**Comment by junxia97** [comment]
您好，可能你的扰动幅度设置的过大了，导致损失函数 (原文 Eq. 4) 分子大于分母。一般而言，分子不会大于分母。

**Comment by ghj9922** [comment]
> 

好的，我再尝试一下，非常感谢！

> 您好，可能你的扰动幅度设置的过大了，导致损失函数 (原文 Eq. 4) 分子大于分母。一般而言，分子不会大于分母。
